collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
description: Documentation for CS50's tools.
exclude: 
  - "application.py"
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "passenger_wsgi.py"
  - "server.conf"
  - "vendor"
host: 0.0.0.0
port: 8080
title: CS50 Documentation
titles_from_headings:
  collections: true
