exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
gems:
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jemoji
host: 0.0.0.0
port: 8080
